export const PermissionsList = [
  'ACCESS_DASHBOARD_PERMISSION',
  'VIEW_LANDING_PAGE_PERMISSION',
  'CUSTOMERS_PERMISSION',
  'SERVICES_PERMISSION',
  'EMPLOYEES_PERMISSION',
  'BRANCH_SETTINGS_PERMISSION',
  'VIEW_REPORTS_PERMISSION',
  'COUPONS_PERMISSION',
] as const;
